name: Deploy to S3

on:
  push:
    branches:
      - master # main 브랜치에서 푸시가 발생하면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub에서 소스 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS CLI 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # S3 버킷이 생성된 리전

      # 3. S3로 파일 동기화
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://sssssssssssssssssssssssssssss  --delete
